/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate user & issue HTTP-only JWT cookie + Bearer token */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out active user & clear session cookie */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get profile details of the currently authenticated user */
        get: operations["AuthController_getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of all partner schools for dropdown pickers */
        get: operations["SchoolsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of programs (optionally filtered by schoolId) for dropdown pickers */
        get: operations["ProgramsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get list of partner agencies for filter pickers */
        get: operations["AgentsController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter applications with tenant-isolated scoping (RBAC) */
        get: operations["ApplicationsController_findAll"];
        put?: never;
        /** Create new student application (Auto-assigns agent for AGENT role) */
        post: operations["ApplicationsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get single application details with relations (RBAC scoped) */
        get: operations["ApplicationsController_findOne"];
        put?: never;
        post?: never;
        /** Delete application record (Admin only) */
        delete: operations["ApplicationsController_remove"];
        options?: never;
        head?: never;
        /** Update application details / stage (Auto-tracks stageEnteredDate) */
        patch: operations["ApplicationsController_update"];
        trace?: never;
    };
    "/api/applications/{id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update application notes (Live auto-save support) */
        patch: operations["ApplicationsController_updateNotes"];
        trace?: never;
    };
    "/ai/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Execute a natural language grounded AI diagnostic query
         * @description Converts admissions questions into deterministic PostgreSQL aggregation tool calls. Backed by Google Gemini Flash and optional Langfuse tracing.
         */
        post: operations["AiController_diagnose"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginDto: {
            /**
             * @description User email address
             * @example admin@tracker.com
             */
            email: string;
            /**
             * @description User password
             * @example password123
             */
            password: string;
        };
        UserResponseDto: {
            /**
             * @description User unique ID (UUID)
             * @example 9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d
             */
            id: string;
            /**
             * @description User email address
             * @example admin@tracker.com
             */
            email: string;
            /**
             * @description User authorization role
             * @example ADMIN
             * @enum {string}
             */
            role: "ADMIN" | "AGENT";
            /**
             * @description Associated Agent ID (UUID) if role is AGENT
             * @example a1111111-1111-1111-1111-111111111111
             */
            agentId?: string;
        };
        LoginResponseDto: {
            /** @description Authenticated user profile */
            user: components["schemas"]["UserResponseDto"];
            /**
             * @description JWT Access Token for Bearer header auth
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
        };
        SchoolResponseDto: {
            /**
             * @description School UUID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description School Name
             * @example University of Toronto
             */
            name: string;
            /**
             * @description School Country
             * @example Canada
             */
            country: string;
        };
        ProgramResponseDto: {
            /**
             * @description Program UUID
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            id: string;
            /**
             * @description School UUID
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            schoolId: string;
            /**
             * @description Program Name
             * @example MSc Computer Science
             */
            name: string;
            /**
             * @description Annual Tuition in USD
             * @example 28000
             */
            tuitionUsd: number;
            /** @description Parent School details */
            school?: components["schemas"]["SchoolResponseDto"];
        };
        AgentResponseDto: {
            /**
             * @description Agent UUID
             * @example a1111111-1111-1111-1111-111111111111
             */
            id: string;
            /**
             * @description Agency Name
             * @example Global Education Pathways
             */
            name: string;
            /**
             * @description Agent Country
             * @example India
             */
            country: string;
            /**
             * @description Agent Performance Tier
             * @example Gold
             * @enum {string}
             */
            tier: "Bronze" | "Silver" | "Gold";
        };
        ApplicationResponseDto: {
            /**
             * @description Application unique ID (UUID)
             * @example 770e8400-e29b-41d4-a716-446655440002
             */
            id: string;
            /**
             * @description Student Name
             * @example Aarav Sharma
             */
            studentName: string;
            /**
             * @description Agent ID (UUID)
             * @example a1111111-1111-1111-1111-111111111111
             */
            agentId: string;
            /**
             * @description Program ID (UUID)
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            programId: string;
            /**
             * @description Application Stage
             * @example Applied
             * @enum {string}
             */
            stage: "Lead" | "Shortlisted" | "Applied" | "Offer Received" | "Accepted" | "Visa Applied" | "Visa Issued" | "Enrolled" | "Withdrawn";
            /**
             * Format: date-time
             * @description Date current stage was entered
             * @example 2026-03-15T08:30:00.000Z
             */
            stageEnteredDate: string;
            /**
             * Format: date-time
             * @description Application creation date
             * @example 2026-01-10T10:00:00.000Z
             */
            createdDate: string;
            /**
             * @description Counselor or internal notes
             * @example Documents submitted for review.
             */
            notes?: string;
            /**
             * Format: date-time
             * @description Record creation timestamp
             * @example 2026-01-10T10:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description Record last updated timestamp
             * @example 2026-03-15T08:30:00.000Z
             */
            updatedAt: string;
            /** @description Associated Partner Agent details */
            agent?: components["schemas"]["AgentResponseDto"];
            /** @description Associated Program details */
            program?: components["schemas"]["ProgramResponseDto"];
        };
        PaginatedResponseMetaDto: {
            /**
             * @description Total number of items matching filters
             * @example 226
             */
            total: number;
            /**
             * @description Current page number
             * @example 1
             */
            page: number;
            /**
             * @description Items per page limit
             * @example 50
             */
            limit: number;
            /**
             * @description Total number of pages
             * @example 5
             */
            totalPages: number;
        };
        PaginatedApplicationsResponseDto: {
            /** @description List of applications for current page */
            items: components["schemas"]["ApplicationResponseDto"][];
            /** @description Pagination metadata */
            meta: components["schemas"]["PaginatedResponseMetaDto"];
        };
        CreateApplicationDto: {
            /**
             * @description Student Full Name
             * @example Arun Sharma
             */
            studentName: string;
            /**
             * @description Program ID (UUID)
             * @example 660e8400-e29b-41d4-a716-446655440001
             */
            programId: string;
            /**
             * @description Agent ID (UUID) - automatically populated for AGENT role users
             * @example a1111111-1111-1111-1111-111111111111
             */
            agentId?: string;
            /**
             * @description Initial application pipeline stage
             * @default Lead
             * @example Lead
             * @enum {string}
             */
            stage: "Lead" | "Shortlisted" | "Applied" | "Offer Received" | "Accepted" | "Visa Applied" | "Visa Issued" | "Enrolled" | "Withdrawn";
            /**
             * @description Optional counselor or admissions notes
             * @example Student has IELTS 7.5 and completed undergraduate degree in IT.
             */
            notes?: string;
        };
        UpdateApplicationDto: {
            /**
             * @description Updated Student Full Name
             * @example Arun Kumar Sharma
             */
            studentName?: string;
            /**
             * @description Updated pipeline stage
             * @example Offer Received
             * @enum {string}
             */
            stage?: "Lead" | "Shortlisted" | "Applied" | "Offer Received" | "Accepted" | "Visa Applied" | "Visa Issued" | "Enrolled" | "Withdrawn";
        };
        UpdateNotesDto: {
            /**
             * @description Updated application notes
             * @example Visa appointment booked for October 15th.
             */
            notes?: string;
        };
        AiQueryDto: {
            /**
             * @description Natural language question regarding student applications, bottlenecks, or performance.
             * @example Why are Gold-tier agents converting faster than Bronze?
             */
            question: string;
        };
        AiDiagnosticResponseDto: {
            /**
             * @description Grounded analytical explanation generated by Gemini based strictly on database numbers.
             * @example Gold-tier agents achieve a 72.0% conversion rate with an average time-to-enrollment of 8.2 days...
             */
            prose: string;
            /**
             * @description The specific PostgreSQL diagnostic tool executed to ground this response.
             * @example get_tier_conversion_comparison
             * @enum {string}
             */
            toolName: "get_tier_conversion_comparison" | "get_stage_bottlenecks_by_program" | "get_agent_performance_ranking" | "get_application_stage_distribution";
            /**
             * @description Raw SQL aggregation rows backing the prose explanation.
             * @example [
             *       {
             *         "tier": "Gold",
             *         "totalApplications": 50,
             *         "enrolledCount": 36,
             *         "conversionRatePct": 72,
             *         "avgDaysToEnroll": 8.2
             *       }
             *     ]
             */
            supportingData: string[];
            /**
             * @description Human-readable summary of the SQL aggregation performed.
             * @example Aggregated total applications, enrolled count, conversion rate %, and average days to enrollment grouped by agent tier.
             */
            sqlQuerySummary: string;
            /**
             * @description Total execution time in milliseconds.
             * @example 1245
             */
            executionTimeMs: number;
            /**
             * @description Langfuse trace identifier if observability is configured.
             * @example trace_cm1234567890
             */
            traceId?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description User successfully authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponseDto"];
                };
            };
            /** @description Invalid input payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponseDto"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SchoolsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alphabetically sorted list of schools */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolResponseDto"][];
                };
            };
        };
    };
    ProgramsController_findAll: {
        parameters: {
            query?: {
                /** @description Filter programs by School ID (UUID) */
                schoolId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alphabetically sorted list of programs */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramResponseDto"][];
                };
            };
        };
    };
    AgentsController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Alphabetically sorted list of agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentResponseDto"][];
                };
            };
        };
    };
    ApplicationsController_findAll: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Number of items per page */
                limit?: number;
                /** @description Filter applications by stage */
                stage?: "Lead" | "Shortlisted" | "Applied" | "Offer Received" | "Accepted" | "Visa Applied" | "Visa Issued" | "Enrolled" | "Withdrawn";
                /** @description Filter applications by School ID (UUID) */
                schoolId?: string;
                /** @description Filter applications by Program ID (UUID) */
                programId?: string;
                /** @description Filter applications by Agent ID (UUID) - Admin only */
                agentId?: string;
                /** @description Search string matching student name (case-insensitive) */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of applications matching search and filter criteria */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedApplicationsResponseDto"];
                };
            };
        };
    };
    ApplicationsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApplicationDto"];
            };
        };
        responses: {
            /** @description Application successfully created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponseDto"];
                };
            };
            /** @description Validation failed */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application details with program and agent info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponseDto"];
                };
            };
            /** @description Forbidden: application belongs to another agent */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Application not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application deleted successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden: Admin access required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Application not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateApplicationDto"];
            };
        };
        responses: {
            /** @description Application updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponseDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Application not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ApplicationsController_updateNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Application UUID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNotesDto"];
            };
        };
        responses: {
            /** @description Notes updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationResponseDto"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Application not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AiController_diagnose: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiQueryDto"];
            };
        };
        responses: {
            /** @description Grounded analytical diagnosis and supporting raw database figures */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiDiagnosticResponseDto"];
                };
            };
            /** @description Missing GEMINI_API_KEY, invalid input, or unsupported off-domain question */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthenticated — valid JWT required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden — Agent attempting to access organization-wide metrics */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
