import { ApiProperty } from '@nestjs/swagger';

export enum AiToolName {
  GET_TIER_CONVERSION = 'get_tier_conversion_comparison',
  GET_STAGE_BOTTLENECKS = 'get_stage_bottlenecks_by_program',
  GET_AGENT_RANKINGS = 'get_agent_performance_ranking',
  GET_STAGE_DISTRIBUTION = 'get_application_stage_distribution',
}

export class AiDiagnosticResponseDto {
  @ApiProperty({
    description:
      'Grounded analytical explanation generated by Gemini based strictly on database numbers.',
    example:
      'Gold-tier agents achieve a 72.0% conversion rate with an average time-to-enrollment of 8.2 days...',
  })
  prose: string;

  @ApiProperty({
    enum: AiToolName,
    description: 'The specific PostgreSQL diagnostic tool executed to ground this response.',
    example: AiToolName.GET_TIER_CONVERSION,
  })
  toolName: AiToolName;

  @ApiProperty({
    description: 'Raw SQL aggregation rows backing the prose explanation.',
    example: [
      {
        tier: 'Gold',
        totalApplications: 50,
        enrolledCount: 36,
        conversionRatePct: 72.0,
        avgDaysToEnroll: 8.2,
      },
    ],
  })
  supportingData: Array<Record<string, any>>;

  @ApiProperty({
    description: 'Human-readable summary of the SQL aggregation performed.',
    example:
      'Aggregated total applications, enrolled count, conversion rate %, and average days to enrollment grouped by agent tier.',
  })
  sqlQuerySummary: string;

  @ApiProperty({
    description: 'Total execution time in milliseconds.',
    example: 1245,
  })
  executionTimeMs: number;

  @ApiProperty({
    required: false,
    description: 'Langfuse trace identifier if observability is configured.',
    example: 'trace_cm1234567890',
  })
  traceId?: string;
}
